services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-Dev
    environment:
      NODE_DB_URI: mongodb://mongo/habitrpg
      LOGGLY_CLIENT_TOKEN: ""   # disables Loggly analytics in dev
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - habitica
    volumes:
      - ./server:/usr/src/habitica/server:z
    command: ["npm", "start"]

  client-dev:
    build:
      context: .
      dockerfile: Dockerfile-Dev
    command: ["npm", "run", "client:dev:docker"]
    environment:
      BASE_URL: http://localhost:3000
      VITE_DEV_SERVER_HOST: 0.0.0.0  # listen on all interfaces for LAN
      LOGGLY_CLIENT_TOKEN: ""         # disables Loggly analytics
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - habitica
    volumes:
      - .:/usr/src/habitica:z
      - /usr/src/habitica/node_modules
      - /usr/src/habitica/website/client/node_modules

  mongo:
    image: mongo:7.0
    container_name: habitica-mongodb
    hostname: mongodb
    networks:
      - habitica
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./mongodb-data-docker:/data/db:z
    entrypoint:
      - "/usr/bin/mongod"
      - "--bind_ip_all"
      - "--replSet"
      - "rs"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      retries: 30

networks:
  habitica:
    driver: bridge